#:schema node_modules/wrangler/config-schema.json
name = "xget"
main = "src/index.js"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
[observability]
enabled = true
head_sampling_rate = 1
[placement]
mode = "smart"
# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
